spring:

  thymeleaf:
    enabled: true
    encoding: UTF-8
    cache: false
    check-template: true
    check-template-location: true
    mode: HTML
    template-resolver-order: 0



server:
  port: 8081